In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Datasets\50_Startups.csv")
df.shape

(50, 5)

In [4]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
df.tail()

R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40

In [6]:
df.corr

<bound method DataFrame.corr of     R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida

In [7]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [10]:
df.columns=['R&DSpend', 'Administration', 'MarketingSpend', 'State', 'Profit']


In [11]:
df

R&DSpend  Administration  MarketingSpend       State     Profit
0   165349.20       136897.80       471784.10    New York  192261.83
1   162597.70       151377.59       443898.53  California  191792.06
2   153441.51       101145.55       407934.54     Florida  191050.39
3   144372.41       118671.85       383199.62    New York  182901.99
4   142107.34        91391.77       366168.42     Florida  166187.94
5   131876.90        99814.71       362861.36    New York  156991.12
6   134615.46       147198.87       127716.82  California  156122.51
7   130298.13       145530.06       323876.68     Florida  155752.60
8   120542.52       148718.95       311613.29    New York  152211.77
9   123334.88       108679.17       304981.62  California  149759.96
10  101913.08       110594.11       229160.95     Florida  146121.95
11  100671.96        91790.61       249744.55  California  144259.40
12   93863.75       127320.38       249839.44     Florida  141585.52
13   91992.39       135495.07       252664.93  California  134307.35
14  119943.24       156547.42       256512.92     Florida  132602.65
15  114523.61       122616.84       261776.23    New York  129917.04
16   78013.11       121597.55       264346.06  California  126992.93
17   94657.16       145077.58       282574.31    New York  125370.37
18   91749.16       114175.79       294919.57     Florida  124266.90
19   86419.70       153514.11            0.00    New York  122776.86
20   76253.86       113867.30       298664.47  California  118474.03
21   78389.47       153773.43       299737.29    New York  111313.02
22   73994.56       122782.75       303319.26     Florida  110352.25
23   67532.53       105751.03       304768.73     Florida  108733.99
24   77044.01        99281.34       140574.81    New York  108552.04
25   64664.71       139553.16       137962.62  California  107404.34
26   75328.87       144135.98       134050.07     Florida  105733.54
27   72107.60       127864.55       353183.81    New York  105008.31
28   66051.52       182645.56       118148.20     Florida  103282.38
29   65605.48       153032.06       107138.38    New York  101004.64
30   61994.48       115641.28        91131.24     Florida   99937.59
31   61136.38       152701.92        88218.23    New York   97483.56
32   63408.86       129219.61        46085.25  California   97427.84
33   55493.95       103057.49       214634.81     Florida   96778.92
34   46426.07       157693.92       210797.67  California   96712.80
35   46014.02        85047.44       205517.64    New York   96479.51
36   28663.76       127056.21       201126.82     Florida   90708.19
37   44069.95        51283.14       197029.42  California   89949.14
38   20229.59        65947.93       185265.10    New York   81229.06
39   38558.51        82982.09       174999.30  California   81005.76
40   28754.33       118546.05       172795.67  California   78239.91
41   27892.92        84710.77       164470.71     Florida   77798.83
42   23640.93        96189.63       148001.11  California   71498.49
43   15505.73       127382.30        35534.17    New York   69758.98
44   22177.74       154806.14        28334.72  California   65200.33
45    1000.23       124153.04         1903.93    New York   64926.08
46    1315.46       115816.21       297114.46     Florida   49490.75
47       0.00       135426.92            0.00  California   42559.73
48     542.05        51743.15            0.00    New York   35673.41
49       0.00       116983.80        45173.06  California   14681.40

In [13]:
X=df[['R&DSpend','Administration','MarketingSpend']]
X.head()

R&DSpend  Administration  MarketingSpend
0  165349.20       136897.80       471784.10
1  162597.70       151377.59       443898.53
2  153441.51       101145.55       407934.54
3  144372.41       118671.85       383199.62
4  142107.34        91391.77       366168.42

In [15]:
Y=df['Profit']
Y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [17]:
X.shape

(50, 3)

In [24]:
X=df[['R&DSpend','Administration','MarketingSpend']]
Y=df['Profit']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [25]:
X_train.shape

(40, 3)

In [26]:
X_test.shape

(10, 3)

In [27]:
Y_train.shape

(40,)

In [28]:
Y_test.shape

(10,)

In [30]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [31]:
regressor.coef_

array([ 0.78180198, -0.01405907,  0.03585935])

In [32]:
regressor.intercept_

48611.774514042474

In [33]:
regressor.predict(X_test)

array([163322.06478296, 117372.30644794,  58666.26579763, 129163.71252499,
       110850.88621379,  98721.27914135, 110284.5637678 , 130708.20333503,
       127687.07124657, 118483.28881319])

In [34]:
Y_pred_train=regressor.predict(X_train)

In [35]:
Y_pred_test=regressor.predict(X_test)

In [36]:
Y_pred_test

array([163322.06478296, 117372.30644794,  58666.26579763, 129163.71252499,
       110850.88621379,  98721.27914135, 110284.5637678 , 130708.20333503,
       127687.07124657, 118483.28881319])

In [37]:
Y_pred_train

array([ 60217.54003282, 151935.55352036, 115852.92255994, 173555.28202481,
        64790.00930996, 101919.87355462, 149381.11091531, 101592.6919845 ,
        98244.82573237,  71049.18650929,  75125.3719206 ,  75621.65894057,
        97424.91800885, 156364.76940222, 160047.0986927 , 129311.8666525 ,
        98020.82570799,  90759.66655548, 102152.03408945,  70143.62675394,
       145809.80480977, 114016.60079137,  47716.55341666,  83865.6032621 ,
        48586.96723898,  46707.79764431, 117336.23723951,  90249.80436798,
       134950.33331886, 154443.74089604, 181778.90392967, 189520.66068079,
       171557.25072976, 192875.31956672,  76447.14272034,  48308.08958462,
       112490.05115576, 134982.4974732 , 115611.48680747,  89410.10149778])

In [38]:
Y_train

43     69758.98
8     152211.77
27    105008.31
3     182901.99
44     65200.33
28    103282.38
14    132602.65
29    101004.64
33     96778.92
42     71498.49
41     77798.83
40     78239.91
31     97483.56
6     156122.51
7     155752.60
18    124266.90
32     97427.84
35     96479.51
25    107404.34
38     81229.06
15    129917.04
19    122776.86
45     64926.08
39     81005.76
49     14681.40
47     42559.73
20    118474.03
34     96712.80
10    146121.95
9     149759.96
2     191050.39
1     191792.06
4     166187.94
0     192261.83
36     90708.19
48     35673.41
24    108552.04
11    144259.40
22    110352.25
37     89949.14
Name: Profit, dtype: float64

In [39]:
X_train.head()

R&DSpend  Administration  MarketingSpend
43   15505.73       127382.30        35534.17
8   120542.52       148718.95       311613.29
27   72107.60       127864.55       353183.81
3   144372.41       118671.85       383199.62
44   22177.74       154806.14        28334.72

In [40]:
y=(0.78180198*15505.73)+(-0.01405907*127382.30)+(0.03585935*35534.17)+48611.774514042474
y

60217.54049591637

In [41]:
y=(0.78180198*120542.52	)+(-0.01405907*148718.95)+(0.03585935*311613.29)+48611.774514042474
y

151935.55522661709

In [42]:
Y_test

5     156991.12
16    126992.93
46     49490.75
12    141585.52
23    108733.99
30     99937.59
26    105733.54
17    125370.37
13    134307.35
21    111313.02
Name: Profit, dtype: float64

In [43]:
Y_pred_test

array([163322.06478296, 117372.30644794,  58666.26579763, 129163.71252499,
       110850.88621379,  98721.27914135, 110284.5637678 , 130708.20333503,
       127687.07124657, 118483.28881319])

In [44]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [45]:
mse_train=mean_squared_error(Y_train,Y_pred_train)
mse_test=mean_squared_error(Y_test,Y_pred_test)
print(mse_train,"  ",mse_test)

85673710.6890084    52153443.98331848


In [46]:
mae_train=mean_absolute_error(Y_train,Y_pred_train)
mae_test=mean_absolute_error(Y_test,Y_pred_test)
print(mae_train,"  ",mae_test)

6457.824667153213    6456.150334955133


In [47]:
rmse_train=np.sqrt(mean_squared_error(Y_train,Y_pred_train))
rmse_test=np.sqrt(mean_squared_error(Y_test,Y_pred_test))
print(rmse_train,"  ",rmse_test)

9256.009436523302    7221.734139617608


In [48]:
r2_score_train=r2_score(Y_train,Y_pred_train)
r2_score_test=r2_score(Y_test,Y_pred_test)
print(r2_score_train,"  ",r2_score_test)

0.9521784587988192    0.9326210889147235


In [49]:
n_train=X_train.shape[0]
n_train

40

In [50]:
n_test=X_test.shape[0]
n_test

10

In [51]:
p=len(X_train.columns)
p

3

In [52]:
adj_r2_score_train=1-(((1-r2_score_train)*(n_train-1))/(n_train-p-1))
adj_r2_score_test=1-(((1-r2_score_test)*(n_test-1))/(n_test-p-1))
print(adj_r2_score_train*100,"   ",adj_r2_score_test*100)

94.81933303653875     89.89316333720852
