In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\saich\Downloads\ML_Datasets\Position_Salaries.csv")

In [3]:

df.head()
     

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [4]:


df.isna().sum()

Position    0
Level       0
Salary      0
dtype: int64

In [5]:
#Feature Matrix
#X = df.iloc[: , 1:2].values
#y = df.iloc[: , 2:].values
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [6]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [7]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000], dtype=int64)

In [8]:

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10 , random_state=0)
regressor.fit(X,y)

RandomForestRegressor(n_estimators=10, random_state=0)

In [9]:
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [10]:
y_pred=regressor.predict([[5.5]])

In [11]:
y_pred

array([108000.])

In [12]:
y_pred=regressor.predict([[5.5]])

In [13]:
y_pred

array([108000.])

In [14]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split

# Split the data (20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Fit the model
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=3, random_state=0)
regressor.fit(X_train, y_train)

# Predict
y_pred = regressor.predict(X_test)

# Metrics
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred) * 100

# Print results
print(f"R² Score: {r2:.4f}")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"MAPE (Error %): {mape:.2f}%")


R² Score: 0.5868
MAE: 100000.00
MSE: 20000000000.00
MAPE (Error %): 20.00%
